version: '3.8'

services:
  postgres:
    image: postgres
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod
    healthcheck:
      test: pg_isready -U postgres
  api:
    platform: linux/amd64
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./api/:/api/
      - static_volume:/api/api/static
      - media_volume:/api/api/media
    ports:
    - 8000:8000
    env_file:
      - ./api/api/.env.prod
    depends_on:
      - postgres
  apix:
    platform: linux/amd64
    build:
      context: ./apix
      dockerfile: Dockerfile.prod
    volumes:
      - ./apix/:/apix
    ports:
      - "5001:5000"
    # env_file:
    #   - ./apix/.env.dev
    depends_on:
      # - postgres
      - api
  web:
    platform: linux/amd64
    restart: unless-stopped
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    volumes:
      - ./web/:/web
      - /web/node_modules
      - /web/.next
    ports:
      - "3000:3000"
    depends_on:
      - api
      - apix
  nginx:
    image: nginx:1.23-alpine
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static_volume:/api/api/static
      - media_volume:/api/api/media
    ports:
      - 80:80
    depends_on:
      - api

volumes:
  postgres_data:
  static_volume:
  media_volume: