version: '3.8'

services:
  postgres:
    image: postgres
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    healthcheck:
      test: pg_isready -U postgres
  api:
    platform: linux/amd64
    build:
      context: ./api
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000 
    volumes:
      - ./api/:/api/
    ports:
    - 8000:8000
    env_file:
      - ./api/api/.env.dev
    depends_on:
      - postgres
  apix:
    platform: linux/amd64
    build:
      context: ./apix
      dockerfile: Dockerfile
    volumes:
      - ./apix/:/apix
    ports:
      - "5001:5000"
    # env_file:
    #   - ./apix/.env.dev
    depends_on:
      # - postgres
      - api
  web:
    platform: linux/amd64
    restart: unless-stopped
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web/:/web
      - /web/node_modules
      - /web/.next
    ports:
      - "3000:3000"
    depends_on:
      - api
      - apix
volumes:
  postgres_data:
