# Set base image (host OS)
FROM python:3.11-slim

# Allow statements and log messages to immediately appear in the logs
ENV PYTHONUNBUFFERED True

# Set the working directory in the container
ENV APP_HOME /apix

WORKDIR $APP_HOME

COPY . .

# Copy the dependencies file to the working directory
# COPY requirements.txt .

# Install any dependencies
RUN pip install -r requirements.txt

ENV PORT 5001

CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 main:app